# Generated by Django 3.1.7 on 2023-12-28 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='totallikes',
            field=models.IntegerField(default=0),
        ),
    ]
